# Global Framework Settings
# Supported Browsers: chrome, edge
browser=Chrome

# Application URL
site.homePage.url=https://www.nilkamalfurniture.com/
site.homePage.searItem=bookshelves
# Timeouts in Seconds
timeout=20


#login page URL
site.loginPage.url=https://www.nilkamalfurniture.com/account/login?return_url=%2Faccount

#login page Title
site.loginPage.title=Account

#Home Page Title
site.homePage.title=Home Furniture | Office Furniture | Mattresses | Nilkamal Furniture


#Product Page Filter
filter=Best Selling
#Checkout page URL

site.checkoutPage.URL = "https://www.nilkamalfurniture.com/checkouts/"

#ExcelFilePath
excelFilePath=./src/test/resources/testdata/DataDrivenTest.xlsx
excelWriteFilePath=./excel_test_output/TestCasesStatus.xlsx

#Filter
site.productListPage.sortBy= Best Selling
site.productListPage.price= 2000
site.productListPage.category= Storage Cabinets
site.productListPage.material= Material

#product page url
site.productPage.url=https://www.nilkamalfurniture.com/products/nilkamal-halo-5-tier-engineered-wood-storage-cabinet-urban-walnut
